name: flutter_inappwebview
description: Flutter plugin that allows you to incorporate WebView widgets into your Flutter app,
  to use headless WebViews, or to use In-App browsers.
repository: https://github.com/dev-mahmoud-elshenawy/flutter_inappwebview.git
issue_tracker: https://github.com/dev-mahmoud-elshenawy/flutter_inappwebview.git/issues?q=is%3Aopen+is%3Aissue
version: 6.3.0

environment:
  sdk: ">=2.17.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_inappwebview_android
      ios:
        default_package: flutter_inappwebview_ios
      macos:
        default_package: flutter_inappwebview_macos
      web:
        default_package: flutter_inappwebview_web

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_android: 1.0.13
  flutter_inappwebview_ios: 1.0.13
  flutter_inappwebview_macos: 1.0.11
  flutter_inappwebview_web: 1.0.8
